#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
name: ${artifactId}
main: ${package}.${artifactId}
version: 0.1

commands:
   command:
      description: A Command
      usage: /<command> 
